### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by stmitt** [Kitura/BlueRSA#71]
Would it be possible to create a new release that contains https://github.com/Kitura/BlueRSA/pull/70. 

Our Project is using https://github.com/Kitura/Swift-JWT which [references](https://github.com/Kitura/Swift-JWT/blob/master/Package.swift#L31) this repository. Therefore we need a new version of this package to be published in order that the fix will get included.

Thanks for your work.

**Comment by dannys42** [comment]
Will do!

**Comment by dannys42** [comment]
@stmitt Please try out 1.0.201

**Comment by stmitt** [comment]
Thank you very much, 1.0.201 works for us.
