### ISSUE TITLE
CFString issue: The operation couldn't be completed. (CryptorRSA.CryptorRSA.Error error 1.)

### ISSUE THREAD

**Issue by yangyubo** [Kitura/BlueRSA#75]
Commit 842c82f8a00b2dd7466de3a4a08173977809ea49 removes "unneeded" CFString: Hashable extension (#70)

But that may not true. Some of our users reported that latest version of our Mac app shows an error:
```
The operation couldn't be completed. (CryptorRSA.CryptorRSA.Error error 1.)
```

It didn't happen on previous versions, and after revert to older commit ea8374b29211e1f3b938cd1ff798ac6149c3771e , our Mac app functional again.

CFString Hashable extension may be still required for some systems.

User environment:

* Device: Mac mini (later 2014)
* OS: macOS Big Sur 11.5
* Process: 2.6 GHz Dual-Core intel Core i5

Development environment:

* OS: macOS 11.5.1 (20G80)
* Chip: Apple M1
* Xcode Version 12.5.1 (12E507)
* Swift 5.3

**Comment by yangyubo** [comment]
I confirmed that this is not a CryptorRSA issue, `SecKeyGeneratePair` and `SecKeyCreateRandomKey` could fail on some conditions.

Reference: https://developer.apple.com/forums/thread/62847

**Comment by dannys42** [comment]
Thanks for the update!
